---
- name: Default
  hosts: "*-default"
  gather_facts: no
  become: yes

  roles:
    - robertdebock.bootstrap
    - ansible-role-java

- name: OpenJDK 6 JRE
  hosts: "*-openjdk-6-jre"
  gather_facts: no
  become: yes

  vars:
    java_version: 6

  roles:
    - robertdebock.bootstrap
    - ansible-role-java

- name: OpenJDK 7 JRE
  hosts: "*-openjdk-7-jre"
  gather_facts: no
  become: yes

  vars:
    java_version: 7

  roles:
    - robertdebock.bootstrap
    - ansible-role-java

- name: OpenJDK 8 JRE
  hosts: "*-openjdk-8-jre"
  gather_facts: no
  become: yes

  vars:
    java_version: 8

  roles:
    - robertdebock.bootstrap
    - ansible-role-java

- name: OpenJDK 9 JRE
  hosts: "*-openjdk-9-jre"
  gather_facts: no
  become: yes

  vars:
    java_version: 9

  roles:
    - robertdebock.bootstrap
    - ansible-role-java

- name: OpenJDK 10 JRE
  hosts: "*-openjdk-10-jre"
  gather_facts: no
  become: yes

  vars:
    java_version: 10

  roles:
    - robertdebock.bootstrap
    - ansible-role-java

- name: OpenJDK 11 JRE
  hosts: "*-openjdk-11-jre"
  gather_facts: no
  become: yes

  vars:
    java_version: 11

  roles:
    - robertdebock.bootstrap
    - ansible-role-java

- name: OpenJDK 6 JDK
  hosts: "*-openjdk-6-jdk"
  gather_facts: no
  become: yes

  vars:
    java_version: 6
    java_type: jdk

  roles:
    - robertdebock.bootstrap
    - ansible-role-java

- name: OpenJDK 7 JDK
  hosts: "*-openjdk-7-jdk"
  gather_facts: no
  become: yes

  vars:
    java_version: 7
    java_type: jdk

  roles:
    - robertdebock.bootstrap
    - ansible-role-java

- name: OpenJDK 8 JDK
  hosts: "*-openjdk-8-jdk"
  gather_facts: no
  become: yes

  vars:
    java_version: 8
    java_type: jdk

  roles:
    - robertdebock.bootstrap
    - ansible-role-java

- name: OpenJDK 9 JDK
  hosts: "*-openjdk-9-jdk"
  gather_facts: no
  become: yes

  vars:
    java_version: 9
    java_type: jdk

  roles:
    - robertdebock.bootstrap
    - ansible-role-java

- name: OpenJDK 10 JDK
  hosts: "*-openjdk-10-jdk"
  gather_facts: no
  become: yes

  vars:
    java_version: 10
    java_type: jdk

  roles:
    - robertdebock.bootstrap
    - ansible-role-java

- name: OpenJDK 11 JDK
  hosts: "*-openjdk-11-jdk"
  gather_facts: no
  become: yes

  vars:
    java_version: 11
    java_type: jdk

  roles:
    - robertdebock.bootstrap
    - ansible-role-java
