---
- name: Converge
  hosts: all
  gather_facts: no
  become: yes

  roles:
    - robertdebock.bootstrap
    - robertdebock.epel
    - ansible-role-npm

  tasks:
    - name: install package with npm
      npm:
        name: debug
        global: true
