#!/usr/bin/env ansible-playbook
---
- name: Converge
  hosts: all
  gather_facts: no
  become: yes

  vars:
    python_pip_modules:
      - name: ansible

  roles:
    - robertdebock.bootstrap
    - robertdebock.common
    - robertdebock.epel
    - robertdebock.python_pip
    - robertdebock.docker
    - robertdebock.awx
