#!/usr/bin/env ansible-playbook
---
- name: Converge
  hosts: all:!localhost
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.cron
    - role: robertdebock.update
    - role: robertdebock.cis
      # 1.1.6 Ensure separate partition exists for /var (Scored)
      # Vagrant image has no /var.
      cis_var_partition: no
      # 1.1.7 Ensure separate partition exists for /var/tmp (Scored)
      # Vagrant image has no /var/tmp.
      cis_var_tmp_partition: no
      # 1.1.11 Ensure separate partition exists for /var/log (Scored)
      # Vagrant image has no /var/log.
      cis_var_log_partition: no
      # 1.1.12 Ensure separate partition exists for /var/log/audit (Scored)
      # Vagrant image has no /var/log/audit.
      cis_var_log_audit_partition: no
      # 1.1.13 Ensure separate partition exists for /home (Scored)
      # Vagrant image has no /home.
      cis_home_partition: no
