#!/usr/bin/env ansible-playbook
---
- name: Converge
  hosts: all
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.update
    - role: robertdebock.cve_2018_19788
