#!/usr/bin/env ansible-playbook
---
- name: Converge
  hosts: all
  gather_facts: no
  become: yes

  vars:
    mysql_databases:
      - name: mediawiki

    mysql_users:
      - name: mediawiki
        password: mediawiki
        priv: "mediawiki.*:ALL"

  roles:
    - robertdebock.bootstrap
    - robertdebock.epel
    - robertdebock.python_pip
    - robertdebock.httpd
    - robertdebock.php
    - robertdebock.mysql
    - robertdebock.mediawiki
