#!/usr/bin/env ansible-playbook
---
- name: Converge
  hosts: all
  gather_facts: yes
  become: yes

  roles:
    - robertdebock.bootstrap
    - robertdebock.epel
    - robertdebock.python_pip
    - robertdebock.docker
    - robertdebock.kubectl
    - role: robertdebock.sysctl
      sysctl_items:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
    - robertdebock.minikube
