#!/usr/bin/env ansible-playbook
---
- name: Converge
  hosts: all
  become: yes
  gather_facts: no

  vars:
    mysql_databases:
      - name: my_db
        encoding: utf8
        collation: utf8_bin
    mysql_users:
      - name: my_user
        password: my_pass
        priv: "my_db.*:ALL"

  roles:
    - robertdebock.bootstrap
    - robertdebock.mysql
