#!/usr/bin/env ansible-playbook
---
- name: Converge
  hosts: all
  gather_facts: no
  become: yes

  roles:
    - robertdebock.bootstrap
    - robertdebock.epel
    - robertdebock.nginx

  tasks:
    - name: test nginx
      shell: nginx -V > nginx.version
      args:
        creates: nginx.version
