#!/usr/bin/env ansible-playbook
---
- name: Prepare
  hosts: all:!localhost
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.core_dependencies
    - role: robertdebock.buildtools
    - role: robertdebock.epel
    - role: robertdebock.python_pip
    - role: robertdebock.openssl
      openssl_items:
        - name: apache-httpd
          common_name: "{{ ansible_fqdn }}"
    - role: robertdebock.selinux
    - role: robertdebock.httpd
    - role: robertdebock.mysql
      mysql_users:
        - name: admin
          password: "P@s5-W0rd"
          priv: "*.*:ALL"
    - role: robertdebock.php
    - role: robertdebock.phpmyadmin
