#!/usr/bin/env ansible-playbook
---
- name: Converge
  hosts: all
  gather_facts: no
  become: yes

  vars:
    postfix_aliases:
      - name: root
        destination: robert@meinit.nl

  roles:
    - robertdebock.bootstrap
    - robertdebock.common
    - robertdebock.postfix
