#!/usr/bin/env ansible-playbook
---
- name: Converge
  hosts: all:!localhost
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.alternatives
    - role: robertdebock.epel
    - role: robertdebock.update
    - role: robertdebock.python_pip
      python_pip_modules:
        - name: ansible
