#!/usr/bin/env ansible-playbook
---
- name: Converge
  hosts: all
  gather_facts: no
  become: yes

  vars:
    mysql_databases:
      - name: roundcube
    mysql_users:
      - name: roundcube
        password: roundcube
        priv: "roundcube.*:ALL"
    roundcubemail_database_user: roundcube
    roundcubemail_database_password: roundcube
    roundcubemail_database_name: roundcube

  roles:
    - robertdebock.bootstrap
    - robertdebock.epel
    - robertdebock.buildtools
    - robertdebock.python_pip
    - robertdebock.httpd
    - robertdebock.mysql
    - robertdebock.roundcubemail
