#!/usr/bin/env ansible-playbook
---
- name: Converge
  hosts: all
  gather_facts: no
  become: yes

  vars:
    rundeck_address: "{{ ansible_default_ipv4.address }}"

  roles:
    - robertdebock.bootstrap
    - robertdebock.java
    - robertdebock.common
    - robertdebock.rundeck
