#!/usr/bin/env ansible-playbook
---
- name: converge
  hosts: all
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.java
    - role: robertdebock.common
    - role: robertdebock.rundeck
      rundeck_address: "{{ ansible_default_ipv4.address }}"
