#!/usr/bin/env ansible-playbook
---
- name: Converge
  hosts: all
  gather_facts: no
  become: yes

  vars:
    mysql_ignore_docker: no
    httpd_ignore_docker: no
    mysql_databases:
      - name: zabbix
        encoding: utf8
    mysql_users:
      - name: zabbix
        password: zabbix
        priv: "zabbix.*:ALL"
    zabbix_server: present
    zabbix_web: present

  roles:
    - robertdebock.bootstrap
    - robertdebock.epel
    - robertdebock.python_pip
    - robertdebock.php
    - robertdebock.mysql
    - robertdebock.httpd
    - robertdebock.zabbix
